version: '3.8'
services:
  postgres:
    container_name: container-pg
    image: cgr.dev/chainguard/postgres 
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: public 
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - wolfi

volumes:
  postgres-data:

networks:
  wolfi: